### ISSUE TITLE
Generation of villages

### ISSUE THREAD

**Issue by anewri32** [jtorleonstudios/HUB-Better-Villages#17]
I have noticed that when I use this mod, the villages I can find increase significantly, which in vanilla minecraft finding a village is quite difficult. I suggest reviewing this section and correcting it since having so many generated villages takes away their value.

**Comment by VinceKezel** [comment]
Same.
It feels like 5x as many Better Villages than there should be. Can there be a config setting for spawn rate?

**Comment by chrstph3r** [comment]
Maybe its your seed, cause I tested this mod with several seeds and where a village has to be, it is. The villages dont increse with this mod.

**Comment by jtorleonstudios** [comment]
The mod doesn't change any generation parameter (for the moment), I'll do some tests to check but there is little chance that Better Village is responsible, because the mod for the moment only replaces the existing structures, the only point to note is that if you add mods that add their own building to the village, there is a high rate of appearance of the buildings added by the mod (which will be fixed)

Looking forward to test for closure post.

**Comment by jtorleonstudios** [comment]
> Maybe its your seed, cause I tested this mod with several seeds and where a village has to be, it is. The villages dont increse with this mod.

tested, and I can't find the problem. Please provide the mods installed in your configuration to pursue the problem.

Reopen the issues with the info, thanks you for your feedback
